services:
  server:
    build: ./be
    container_name: server
    environment:
      - HOST=0.0.0.0 
      - BE_PORT=${BE_PORT}
    ports:
      - "3001:3001"  
  client:
    build: ./fe
    container_name: client
    environment:
      - VITE_API_URL=http://server:3001
    ports:
      - "5173:5173"
    depends_on:
      - server